#!/usr/bin/expect -f
spawn sudo su -  oracle
send "cp /tmp/mysqlkey.pub ~oracle/.ssh/.\r"
expect "$ "
send "cd ~oracle/.ssh\r"
expect "$ "
send "cat authorized_keys mysqlkey.pub > authorized_keys_tmp\r"
expect "$ "
send "mv authorized_keys authorized_keys_backup\r"
expect "$ "
send "mv authorized_keys_tmp authorized_keys\r"
expect "$ "
send "rm mysqlkey.pub\r"
expect "$ "
send "exit\r"
